/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ihungryburger.ui.search;

import ihungryburger.ui.DashboardFrame;
import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Dell
 */
public class SearchFrame extends javax.swing.JFrame {
    
    public SearchFrame() {
        initComponents();
        
        ImageIcon originalIcon = new ImageIcon("E://BackUP4/ICD119/Data Structures & Algorithms/Day2/New folder (2)/IHungryBurger/src/resources/iHungryBurger without contiaining Texts.jpg");
        Image originalImage = originalIcon.getImage();
        
        int newWidth = 810;
        int newHeight = 390;
        Image scaledImage = originalImage.getScaledInstance(newWidth, newHeight, Image.SCALE_SMOOTH);
        
        ImageIcon scaledIcon = new ImageIcon(scaledImage);
        backgroundImage.setIcon(scaledIcon);
        
        searchPortalPanel.setComponentZOrder(backgroundImage, searchPortalPanel.getComponentCount() - 1);
        searchPortalPanel.revalidate();
        searchPortalPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchPortalPanel = new javax.swing.JPanel();
        btnSearchBurger = new javax.swing.JButton();
        btnSearchCustomer = new javax.swing.JButton();
        btnSearchBestCustomer = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnBackToHomePage = new javax.swing.JButton();
        lblWelcomeMessage = new javax.swing.JLabel();
        burgerIcon = new javax.swing.JLabel();
        lblWelcomeMessage1 = new javax.swing.JLabel();
        backgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        searchPortalPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSearchBurger.setBackground(new java.awt.Color(255, 255, 0));
        btnSearchBurger.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnSearchBurger.setText("SEARCH BURGER");
        btnSearchBurger.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnSearchBurger.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchBurgerActionPerformed(evt);
            }
        });
        searchPortalPanel.add(btnSearchBurger, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 168, 180, -1));

        btnSearchCustomer.setBackground(new java.awt.Color(0, 255, 0));
        btnSearchCustomer.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnSearchCustomer.setText("SEARCH CUSTOMER");
        btnSearchCustomer.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnSearchCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCustomerActionPerformed(evt);
            }
        });
        searchPortalPanel.add(btnSearchCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 208, 180, -1));

        btnSearchBestCustomer.setBackground(new java.awt.Color(0, 255, 204));
        btnSearchBestCustomer.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnSearchBestCustomer.setText("SEARCH BEST CUSTOMER");
        btnSearchBestCustomer.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnSearchBestCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchBestCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchBestCustomerActionPerformed(evt);
            }
        });
        searchPortalPanel.add(btnSearchBestCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 248, 180, -1));

        btnExit.setBackground(new java.awt.Color(255, 0, 0));
        btnExit.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.setLabel("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        searchPortalPanel.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 333, 84, -1));

        btnBackToHomePage.setBackground(new java.awt.Color(0, 51, 255));
        btnBackToHomePage.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnBackToHomePage.setForeground(new java.awt.Color(255, 255, 255));
        btnBackToHomePage.setText("Back To Home Page");
        btnBackToHomePage.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnBackToHomePage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackToHomePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToHomePageActionPerformed(evt);
            }
        });
        searchPortalPanel.add(btnBackToHomePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 333, 159, -1));

        lblWelcomeMessage.setFont(new java.awt.Font("Haettenschweiler", 0, 48)); // NOI18N
        lblWelcomeMessage.setForeground(new java.awt.Color(102, 102, 255));
        lblWelcomeMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcomeMessage.setText("iHungryBurger - Search Portal");
        searchPortalPanel.add(lblWelcomeMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        burgerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/burger.png"))); // NOI18N
        searchPortalPanel.add(burgerIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        lblWelcomeMessage1.setFont(new java.awt.Font("Haettenschweiler", 0, 24)); // NOI18N
        lblWelcomeMessage1.setForeground(new java.awt.Color(0, 0, 204));
        lblWelcomeMessage1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcomeMessage1.setText("Search Menu Area");
        searchPortalPanel.add(lblWelcomeMessage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));
        searchPortalPanel.add(backgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchPortalPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchPortalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackToHomePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToHomePageActionPerformed
        dispose();
        new DashboardFrame().setVisible(true);
    }//GEN-LAST:event_btnBackToHomePageActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        dispose();
        new DashboardFrame().setVisible(true);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSearchBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchBurgerActionPerformed
        dispose();
        new SearchBurgerFrame().setVisible(true);
    }//GEN-LAST:event_btnSearchBurgerActionPerformed

    private void btnSearchCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCustomerActionPerformed
        dispose();
        new SearchCustomerFrame().setVisible(true);
    }//GEN-LAST:event_btnSearchCustomerActionPerformed

    private void btnSearchBestCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchBestCustomerActionPerformed
        try {
            dispose();
            new SearchBestCustomerFrame().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(SearchFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSearchBestCustomerActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JButton btnBackToHomePage;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSearchBestCustomer;
    private javax.swing.JButton btnSearchBurger;
    private javax.swing.JButton btnSearchCustomer;
    private javax.swing.JLabel burgerIcon;
    private javax.swing.JLabel lblWelcomeMessage;
    private javax.swing.JLabel lblWelcomeMessage1;
    private javax.swing.JPanel searchPortalPanel;
    // End of variables declaration//GEN-END:variables
}
