/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ihungryburger.ui.panels;

import ihungryburger.ui.MainFrame;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Dell
 */
public class DashboardPanel extends javax.swing.JPanel {
    private MainFrame mainFrame;
    /**
     * Creates new form DashboardPanel
     * @param mainFrame
     */
    public DashboardPanel(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Image img = new ImageIcon(getClass().getResource("/ihungryburger/resources/iHungryBurger.jpg")).getImage();
        g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        burgerIcon = new javax.swing.JLabel();
        lblWelcomeMessage = new javax.swing.JLabel();
        btnPlaceOrder = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnViewOrders = new javax.swing.JButton();
        btnUpdateOrderDetails = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        footer = new javax.swing.JLabel();
        btnClose = new javax.swing.JLabel();

        burgerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ihungryburger/resources/burger.png"))); // NOI18N

        lblWelcomeMessage.setFont(new java.awt.Font("Haettenschweiler", 0, 48)); // NOI18N
        lblWelcomeMessage.setForeground(new java.awt.Color(102, 102, 255));
        lblWelcomeMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcomeMessage.setText("iHungryBurger");

        btnPlaceOrder.setBackground(new java.awt.Color(51, 204, 0));
        btnPlaceOrder.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnPlaceOrder.setText("PLACE ORDER");
        btnPlaceOrder.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnPlaceOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(255, 255, 0));
        btnSearch.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.setLabel("SEARCH");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnViewOrders.setBackground(new java.awt.Color(0, 255, 255));
        btnViewOrders.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnViewOrders.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnViewOrders.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewOrders.setLabel("VIEW ORDERS");
        btnViewOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewOrdersActionPerformed(evt);
            }
        });

        btnUpdateOrderDetails.setBackground(new java.awt.Color(255, 0, 255));
        btnUpdateOrderDetails.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnUpdateOrderDetails.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnUpdateOrderDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateOrderDetails.setLabel("UPDATE ORDER DETAILS");
        btnUpdateOrderDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateOrderDetailsActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 0, 0));
        btnExit.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.setLabel("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        footer.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        footer.setForeground(new java.awt.Color(255, 255, 255));
        footer.setText("© 2025 iHungryBurger Inc | Version 3.0");

        btnClose.setBackground(new java.awt.Color(255, 0, 0));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ihungryburger/resources/close-btn.png"))); // NOI18N
        btnClose.setToolTipText("");
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(burgerIcon)
                        .addGap(18, 18, 18)
                        .addComponent(lblWelcomeMessage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(footer, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnPlaceOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(btnViewOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(btnUpdateOrderDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClose)
                    .addComponent(lblWelcomeMessage)
                    .addComponent(burgerIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPlaceOrder)
                    .addComponent(btnSearch)
                    .addComponent(btnViewOrders)
                    .addComponent(btnUpdateOrderDetails))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(footer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit))
                .addGap(13, 13, 13))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
        mainFrame.showPanel("place");
    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        mainFrame.showPanel("search");
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnViewOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewOrdersActionPerformed
        mainFrame.showPanel("viewBurgers");
    }//GEN-LAST:event_btnViewOrdersActionPerformed

    private void btnUpdateOrderDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateOrderDetailsActionPerformed
        mainFrame.showPanel("updateStatus");
    }//GEN-LAST:event_btnUpdateOrderDetailsActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        mainFrame.dispose();
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        mainFrame.dispose();
        System.exit(0);
    }//GEN-LAST:event_btnCloseMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClose;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdateOrderDetails;
    private javax.swing.JButton btnViewOrders;
    private javax.swing.JLabel burgerIcon;
    private javax.swing.JLabel footer;
    private javax.swing.JLabel lblWelcomeMessage;
    // End of variables declaration//GEN-END:variables
}
