/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ihungryburger.ui.panels.view;

import ihungryburger.ui.MainFrame;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Dell
 */
public class ViewBurgersPanel extends javax.swing.JPanel {
    private MainFrame mainFrame;
    /**
     * Creates new form ViewOrdersPanel
     * @param mainFrame
     */
    public ViewBurgersPanel(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        
        Image img = new ImageIcon(getClass().getResource("/ihungryburger/resources/iHungryBurger without contiaining Texts.jpg")).getImage();
        g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcomeMessage = new javax.swing.JLabel();
        lblWelcomeMessage1 = new javax.swing.JLabel();
        btnDelivered = new javax.swing.JButton();
        btnPreparing = new javax.swing.JButton();
        btnCanceled = new javax.swing.JButton();
        btnBackToHomePage = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        burgerIcon = new javax.swing.JLabel();
        btnClose = new javax.swing.JLabel();

        lblWelcomeMessage.setFont(new java.awt.Font("Haettenschweiler", 0, 48)); // NOI18N
        lblWelcomeMessage.setForeground(new java.awt.Color(102, 102, 255));
        lblWelcomeMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcomeMessage.setText("iHungryBurger - View Portal");

        lblWelcomeMessage1.setFont(new java.awt.Font("Haettenschweiler", 0, 24)); // NOI18N
        lblWelcomeMessage1.setForeground(new java.awt.Color(0, 0, 204));
        lblWelcomeMessage1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcomeMessage1.setText("Search Menu Area");

        btnDelivered.setBackground(new java.awt.Color(255, 204, 0));
        btnDelivered.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnDelivered.setForeground(new java.awt.Color(255, 255, 255));
        btnDelivered.setText("DELIVERED");
        btnDelivered.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnDelivered.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelivered.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeliveredActionPerformed(evt);
            }
        });

        btnPreparing.setBackground(new java.awt.Color(0, 255, 0));
        btnPreparing.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnPreparing.setForeground(new java.awt.Color(255, 255, 255));
        btnPreparing.setText("PREPARING");
        btnPreparing.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnPreparing.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPreparing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreparingActionPerformed(evt);
            }
        });

        btnCanceled.setBackground(new java.awt.Color(255, 0, 0));
        btnCanceled.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnCanceled.setForeground(new java.awt.Color(255, 255, 255));
        btnCanceled.setText("CANCELED");
        btnCanceled.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnCanceled.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCanceled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanceledActionPerformed(evt);
            }
        });

        btnBackToHomePage.setBackground(new java.awt.Color(0, 51, 255));
        btnBackToHomePage.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnBackToHomePage.setForeground(new java.awt.Color(255, 255, 255));
        btnBackToHomePage.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnBackToHomePage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackToHomePage.setLabel("BACK TO HOME PAGE");
        btnBackToHomePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToHomePageActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 0, 0));
        btnExit.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.setLabel("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        burgerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ihungryburger/resources/burger.png"))); // NOI18N

        btnClose.setBackground(new java.awt.Color(255, 0, 0));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ihungryburger/resources/close-btn.png"))); // NOI18N
        btnClose.setText("sdf");
        btnClose.setToolTipText("");
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblWelcomeMessage1)
                            .addComponent(btnDelivered, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPreparing, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCanceled, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(burgerIcon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblWelcomeMessage)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(208, 208, 208)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBackToHomePage, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(burgerIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWelcomeMessage)
                    .addComponent(btnClose))
                .addGap(38, 38, 38)
                .addComponent(lblWelcomeMessage1)
                .addGap(23, 23, 23)
                .addComponent(btnDelivered)
                .addGap(18, 18, 18)
                .addComponent(btnPreparing)
                .addGap(18, 18, 18)
                .addComponent(btnCanceled)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBackToHomePage)
                    .addComponent(btnExit))
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeliveredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeliveredActionPerformed
        mainFrame.showPanel("delivered");
    }//GEN-LAST:event_btnDeliveredActionPerformed

    private void btnPreparingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreparingActionPerformed
        mainFrame.showPanel("preparing");
    }//GEN-LAST:event_btnPreparingActionPerformed

    private void btnCanceledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanceledActionPerformed
        mainFrame.showPanel("canceled");
    }//GEN-LAST:event_btnCanceledActionPerformed

    private void btnBackToHomePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToHomePageActionPerformed
        mainFrame.showPanel("dashboard");
    }//GEN-LAST:event_btnBackToHomePageActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        mainFrame.dispose();
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        mainFrame.dispose();
        System.exit(0);
    }//GEN-LAST:event_btnCloseMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToHomePage;
    private javax.swing.JButton btnCanceled;
    private javax.swing.JLabel btnClose;
    private javax.swing.JButton btnDelivered;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPreparing;
    private javax.swing.JLabel burgerIcon;
    private javax.swing.JLabel lblWelcomeMessage;
    private javax.swing.JLabel lblWelcomeMessage1;
    // End of variables declaration//GEN-END:variables
}
