/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ihungryburger.ui.view;

import ihungryburger.ui.view.PreparingFrame;
import ihungryburger.ui.view.CanceledFrame;
import ihungryburger.ui.view.DeliveredFrame;
import ihungryburger.service.BurgerCollection;

/**
 *
 * @author Dell
 */
public class ViewOrdersFrame extends javax.swing.JFrame {
    public BurgerCollection burgerCollection;
    /**
     * Creates new form DashboardFrame
     * @param burgerCollection
     */
    public ViewOrdersFrame(BurgerCollection burgerCollection) {
        initComponents();
        this.burgerCollection = burgerCollection;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnDelivered = new javax.swing.JButton();
        btnPreparing = new javax.swing.JButton();
        btnCanceled = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnBackToHomePage = new javax.swing.JButton();
        lblWelcomeMessage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnDelivered.setBackground(new java.awt.Color(255, 0, 0));
        btnDelivered.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnDelivered.setForeground(new java.awt.Color(255, 255, 255));
        btnDelivered.setText("DELIVERED");
        btnDelivered.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnDelivered.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeliveredActionPerformed(evt);
            }
        });

        btnPreparing.setBackground(new java.awt.Color(255, 0, 0));
        btnPreparing.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnPreparing.setForeground(new java.awt.Color(255, 255, 255));
        btnPreparing.setText("PREPARING");
        btnPreparing.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnPreparing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreparingActionPerformed(evt);
            }
        });

        btnCanceled.setBackground(new java.awt.Color(255, 0, 0));
        btnCanceled.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnCanceled.setForeground(new java.awt.Color(255, 255, 255));
        btnCanceled.setText("CANCELED");
        btnCanceled.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnCanceled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanceledActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 0, 0));
        btnExit.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnExit.setLabel("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnBackToHomePage.setBackground(new java.awt.Color(0, 51, 255));
        btnBackToHomePage.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnBackToHomePage.setForeground(new java.awt.Color(255, 255, 255));
        btnBackToHomePage.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnBackToHomePage.setLabel("BACK TO HOME PAGE");
        btnBackToHomePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToHomePageActionPerformed(evt);
            }
        });

        lblWelcomeMessage.setFont(new java.awt.Font("Haettenschweiler", 0, 48)); // NOI18N
        lblWelcomeMessage.setForeground(new java.awt.Color(102, 102, 255));
        lblWelcomeMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcomeMessage.setText("iHungryBurger");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/burger.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnDelivered, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPreparing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCanceled, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBackToHomePage, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(lblWelcomeMessage)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWelcomeMessage)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(btnDelivered)
                .addGap(18, 18, 18)
                .addComponent(btnPreparing)
                .addGap(18, 18, 18)
                .addComponent(btnCanceled)
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBackToHomePage)
                    .addComponent(btnExit))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackToHomePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToHomePageActionPerformed
        dispose();
    }//GEN-LAST:event_btnBackToHomePageActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnDeliveredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeliveredActionPerformed
        new DeliveredFrame(burgerCollection).setVisible(true);
    }//GEN-LAST:event_btnDeliveredActionPerformed

    private void btnPreparingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreparingActionPerformed
        new PreparingFrame(burgerCollection).setVisible(true);
    }//GEN-LAST:event_btnPreparingActionPerformed

    private void btnCanceledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanceledActionPerformed
        new CanceledFrame(burgerCollection).setVisible(true);
    }//GEN-LAST:event_btnCanceledActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToHomePage;
    private javax.swing.JButton btnCanceled;
    private javax.swing.JButton btnDelivered;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPreparing;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblWelcomeMessage;
    // End of variables declaration//GEN-END:variables
}
