/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ihungryburger.ui.update;

import ihungryburger.service.BurgerCollection;
import ihungryburger.model.Burger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class UpdateBurgerStatusFrame extends javax.swing.JFrame {
    public BurgerCollection burgerCollection;
    /**
     * Creates new form DashboardFrame
     * @param burgerCollection
     */
    
    public UpdateBurgerStatusFrame(BurgerCollection burgerCollection) {
        initComponents();
        this.burgerCollection = burgerCollection;
        
        cbOrderStatus.setEnabled(false);
        txtSearchedID.setText("B");
        txtSearchedID.requestFocus();
        
        txtCustomerID.setEnabled(false);
        txtCustomerName.setEnabled(false);
        txtBurgerQty.setEnabled(false);
        
        btnQTYUpdate.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblOrderID = new javax.swing.JLabel();
        lblCustomerID = new javax.swing.JLabel();
        lblBurgerQTY = new javax.swing.JLabel();
        lblOrderStatus = new javax.swing.JLabel();
        lblTotalValue = new javax.swing.JLabel();
        txtCustomerID = new javax.swing.JTextField();
        txtBurgerQty = new javax.swing.JTextField();
        txtCustomerName = new javax.swing.JTextField();
        lblCustomerName = new javax.swing.JLabel();
        txtSearchedID = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        cbOrderStatus = new javax.swing.JComboBox<>();
        lblStatusAlert = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        lblWelcomeMessage = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnBackToHomePage = new javax.swing.JButton();
        btnQTYUpdate = new javax.swing.JButton();
        btnStatusUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblOrderID.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        lblOrderID.setText("Order ID:");

        lblCustomerID.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        lblCustomerID.setText("Customer ID:");

        lblBurgerQTY.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        lblBurgerQTY.setText("Burger QTY:");

        lblOrderStatus.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        lblOrderStatus.setText("Order Status:");

        lblTotalValue.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N

        txtCustomerID.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N

        txtBurgerQty.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N

        txtCustomerName.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N

        lblCustomerName.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        lblCustomerName.setText("Name:");

        txtSearchedID.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        txtSearchedID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchedIDActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        lblTotal.setText("Total");

        cbOrderStatus.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        cbOrderStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DELIVERED", "PREPARING", "CANCELED" }));

        lblStatusAlert.setFont(new java.awt.Font("News701 BT", 0, 9)); // NOI18N
        lblStatusAlert.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblOrderStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbOrderStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBurgerQTY)
                            .addComponent(lblTotal)
                            .addComponent(lblCustomerID)
                            .addComponent(lblOrderID)
                            .addComponent(lblCustomerName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCustomerName)
                                .addComponent(txtCustomerID)
                                .addComponent(txtSearchedID, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(lblTotalValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(txtBurgerQty, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(2, 2, 2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jSeparator2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStatusAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrderStatus)
                    .addComponent(cbOrderStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOrderID)
                            .addComponent(txtSearchedID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCustomerID)
                            .addComponent(txtCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCustomerName)
                            .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBurgerQTY)
                            .addComponent(txtBurgerQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotal)
                            .addComponent(lblTotalValue)))
                    .addComponent(lblStatusAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 0, 0));

        lblWelcomeMessage.setFont(new java.awt.Font("Haettenschweiler", 0, 48)); // NOI18N
        lblWelcomeMessage.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcomeMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcomeMessage.setText("UPDATE BURGER STATUS DETAILS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(lblWelcomeMessage)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblWelcomeMessage)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btnBackToHomePage.setBackground(new java.awt.Color(0, 51, 204));
        btnBackToHomePage.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnBackToHomePage.setForeground(new java.awt.Color(255, 255, 255));
        btnBackToHomePage.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnBackToHomePage.setLabel("BACK TO HOME PAGE");
        btnBackToHomePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToHomePageActionPerformed(evt);
            }
        });

        btnQTYUpdate.setBackground(new java.awt.Color(255, 255, 0));
        btnQTYUpdate.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnQTYUpdate.setText("QTY UPDATE");
        btnQTYUpdate.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnQTYUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQTYUpdateActionPerformed(evt);
            }
        });

        btnStatusUpdate.setBackground(new java.awt.Color(51, 204, 0));
        btnStatusUpdate.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnStatusUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnStatusUpdate.setText("STATUS UPDATE");
        btnStatusUpdate.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnStatusUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatusUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnQTYUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStatusUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBackToHomePage, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnQTYUpdate)
                .addGap(62, 62, 62)
                .addComponent(btnStatusUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBackToHomePage)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnStatusUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatusUpdateActionPerformed
        String updatedStatus = (String) cbOrderStatus.getSelectedItem();
        
        int updatedStatusAsInteger;
        if(updatedStatus.equals("DELIVERED")) {
            updatedStatusAsInteger = Burger.DELIVERED;
        } else if(updatedStatus.equals("CANCELED")) {
            updatedStatusAsInteger = Burger.CANCELED;
        } else {
            updatedStatusAsInteger = Burger.PREPARING;
        }
        
        String searchedID = txtSearchedID.getText();
        int index = burgerCollection.haveAlreadyPlacedBurger(searchedID);
        if(index!=-1) {
            Burger burger = burgerCollection.searchedBurgerForRelevantIndex(index);
            int confirmUpdate = JOptionPane.showConfirmDialog(this, "You're about update the place?", "Confirm Update", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(confirmUpdate==JOptionPane.YES_OPTION) {
                burger.setStatus(updatedStatusAsInteger);
                JOptionPane.showMessageDialog(this, "You have updated the status successfully!", "Status Updated", JOptionPane.INFORMATION_MESSAGE);
                btnQTYUpdate.setEnabled(true);
            } else {
                dispose();
            }
        } else {
                dispose();
        }
    }//GEN-LAST:event_btnStatusUpdateActionPerformed

    private void btnBackToHomePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToHomePageActionPerformed
        dispose();
    }//GEN-LAST:event_btnBackToHomePageActionPerformed

    private void txtSearchedIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchedIDActionPerformed
        String searchedID = txtSearchedID.getText();
        
        int index = burgerCollection.haveAlreadyPlacedBurger(searchedID);
        if(index!=-1) {
            Burger burger = burgerCollection.searchedBurgerForRelevantIndex(index);
            txtCustomerID.setText(burger.getCustomerID());
            txtCustomerName.setText(burger.getCustomerName());
            
            txtBurgerQty.setText(String.valueOf(burger.getBurgerQty()));
            
            lblTotalValue.setText(String.valueOf(burger.getBurgerQty()*Burger.BURGERPRICE));
            
            cbOrderStatus.setEnabled(true);
            String statusInTextMode = burgerCollection.getStatusInTextMode(burger.getStatus());
            cbOrderStatus.setSelectedItem(statusInTextMode);
            if(statusInTextMode.equals("DELIVERED")) {
                lblStatusAlert.setText("This burger has already Delivered! So, you cannot update this burger...");
            } else if(statusInTextMode.equals("CANCELED")) {
                lblStatusAlert.setText("This burger has already Canceled! So, you cannot update this burger...");
            } else {
                lblStatusAlert.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(this, "That's invalid! Try another.", "Invalid Burger", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtSearchedIDActionPerformed

    private void btnQTYUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQTYUpdateActionPerformed
        new UpdateBurgerQTYFrame(burgerCollection).setVisible(true);
    }//GEN-LAST:event_btnQTYUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToHomePage;
    private javax.swing.JButton btnQTYUpdate;
    private javax.swing.JButton btnStatusUpdate;
    private javax.swing.JComboBox<String> cbOrderStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblBurgerQTY;
    private javax.swing.JLabel lblCustomerID;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblOrderID;
    private javax.swing.JLabel lblOrderStatus;
    private javax.swing.JLabel lblStatusAlert;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalValue;
    private javax.swing.JLabel lblWelcomeMessage;
    private javax.swing.JTextField txtBurgerQty;
    private javax.swing.JTextField txtCustomerID;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtSearchedID;
    // End of variables declaration//GEN-END:variables
}
