/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ihungryburger.ui.panels.update;

import ihungryburger.controller.BurgerController;
import ihungryburger.ui.MainFrame;
import ihungryburger.model.Burger;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class UpdateBurgerStatusPanel extends javax.swing.JPanel {
    private MainFrame mainFrame;
    public BurgerController burgerController;
    /**
     * Creates new form UpdateBurgerStatusPanel
     * @param mainFrame
     */
    public UpdateBurgerStatusPanel(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
        burgerController = new BurgerController();
        
        cbOrderStatus.setEnabled(false);
        txtSearchedID.setText("B");
        txtSearchedID.requestFocus();
        
        txtCustomerID.setEnabled(false);
        txtCustomerName.setEnabled(false);
        txtBurgerQty.setEnabled(false);
        
        lblTotalValue.setEnabled(false);
        
        btnStatusUpdate.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcomeMessage = new javax.swing.JLabel();
        lblOrderStatus = new javax.swing.JLabel();
        cbOrderStatus = new javax.swing.JComboBox<>();
        lblOrderID = new javax.swing.JLabel();
        txtSearchedID = new javax.swing.JTextField();
        lblCustomerID = new javax.swing.JLabel();
        txtCustomerID = new javax.swing.JTextField();
        lblCustomerName = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JTextField();
        lblBurgerQTY = new javax.swing.JLabel();
        txtBurgerQty = new javax.swing.JTextField();
        lblTotalValue = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jSeparator = new javax.swing.JSeparator();
        btnQTYUpdate = new javax.swing.JButton();
        btnStatusUpdate = new javax.swing.JButton();
        btnBackToHomePage = new javax.swing.JButton();
        lblStatusAlert = new javax.swing.JLabel();
        burgerIcon = new javax.swing.JLabel();
        btnClose = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 102, 255));

        lblWelcomeMessage.setFont(new java.awt.Font("Haettenschweiler", 0, 48)); // NOI18N
        lblWelcomeMessage.setForeground(new java.awt.Color(204, 204, 255));
        lblWelcomeMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcomeMessage.setText("Burger Status Update - iBurgerHungry");

        lblOrderStatus.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        lblOrderStatus.setText("Order Status:");

        cbOrderStatus.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        cbOrderStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DELIVERED", "PREPARING", "CANCELED" }));
        cbOrderStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOrderStatusActionPerformed(evt);
            }
        });

        lblOrderID.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        lblOrderID.setText("Order ID:");

        txtSearchedID.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        txtSearchedID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchedIDActionPerformed(evt);
            }
        });

        lblCustomerID.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        lblCustomerID.setText("Customer ID:");

        txtCustomerID.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N

        lblCustomerName.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        lblCustomerName.setText("Name:");

        txtCustomerName.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N

        lblBurgerQTY.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        lblBurgerQTY.setText("Burger QTY:");

        txtBurgerQty.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N

        lblTotalValue.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N

        lblTotal.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        lblTotal.setText("Total");

        btnQTYUpdate.setBackground(new java.awt.Color(255, 255, 0));
        btnQTYUpdate.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnQTYUpdate.setText("QTY UPDATE");
        btnQTYUpdate.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnQTYUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQTYUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQTYUpdateActionPerformed(evt);
            }
        });

        btnStatusUpdate.setBackground(new java.awt.Color(51, 204, 0));
        btnStatusUpdate.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnStatusUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnStatusUpdate.setText("STATUS UPDATE");
        btnStatusUpdate.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnStatusUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStatusUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatusUpdateActionPerformed(evt);
            }
        });

        btnBackToHomePage.setBackground(new java.awt.Color(0, 51, 204));
        btnBackToHomePage.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnBackToHomePage.setForeground(new java.awt.Color(255, 255, 255));
        btnBackToHomePage.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnBackToHomePage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackToHomePage.setLabel("BACK TO HOME PAGE");
        btnBackToHomePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToHomePageActionPerformed(evt);
            }
        });

        lblStatusAlert.setFont(new java.awt.Font("News701 BT", 0, 9)); // NOI18N
        lblStatusAlert.setForeground(new java.awt.Color(255, 51, 51));

        burgerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ihungryburger/resources/burger.png"))); // NOI18N

        btnClose.setBackground(new java.awt.Color(255, 0, 0));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ihungryburger/resources/close-btn.png"))); // NOI18N
        btnClose.setToolTipText("");
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addComponent(lblStatusAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblOrderStatus)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbOrderStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblBurgerQTY)
                                            .addComponent(lblTotal)
                                            .addComponent(lblCustomerName)
                                            .addComponent(lblCustomerID)
                                            .addComponent(lblOrderID))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTotalValue, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtBurgerQty, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtCustomerID, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                                                    .addComponent(txtSearchedID))))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnQTYUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnStatusUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnBackToHomePage, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(burgerIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblWelcomeMessage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(burgerIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblWelcomeMessage)
                        .addComponent(btnClose)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOrderStatus)
                            .addComponent(cbOrderStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOrderID)
                            .addComponent(txtSearchedID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCustomerID)
                            .addComponent(txtCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCustomerName)
                            .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBurgerQTY)
                            .addComponent(txtBurgerQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotal)
                            .addComponent(lblTotalValue)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStatusAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnQTYUpdate)
                        .addGap(56, 56, 56)
                        .addComponent(btnStatusUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBackToHomePage)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbOrderStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOrderStatusActionPerformed
        String updatedStatus = (String) cbOrderStatus.getSelectedItem();

        if(updatedStatus.equalsIgnoreCase("PREPARING")) {
            btnStatusUpdate.setEnabled(false);
        } else {
            btnStatusUpdate.setEnabled(true);
        }
    }//GEN-LAST:event_cbOrderStatusActionPerformed

    private void txtSearchedIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchedIDActionPerformed
        String searchedID = txtSearchedID.getText();

        boolean haveAlreadyTaken;
        try {
            haveAlreadyTaken = burgerController.haveAlreadyTaken(searchedID);
            if(haveAlreadyTaken) {
                Burger burger = burgerController.retrieveBurger(searchedID);
                txtCustomerID.setText(burger.getCustomerID());
                txtCustomerName.setText(burger.getCustomerName());

                txtBurgerQty.setText(Integer.toString(burger.getBurgerQty()));

                double total = burger.getBurgerQty()*Burger.BURGERPRICE;
                lblTotalValue.setText(String.valueOf(total));

                String statusInTextMode = burgerController.getStatusInTextMode(burger.getStatus());
                cbOrderStatus.setSelectedItem(statusInTextMode);

                if(statusInTextMode.equals("DELIVERED")) {
                    lblStatusAlert.setText("<html><b>This burger has already Delivered!<b/> So, you cannot update this burger...</html>");

                    cbOrderStatus.setEnabled(false);
                    btnStatusUpdate.setEnabled(false);
                } else if(statusInTextMode.equals("CANCELED")) {
                    lblStatusAlert.setText("<html><b>This burger has already Canceled!<b/> So, you cannot update this burger...</html>");

                    cbOrderStatus.setEnabled(false);
                    btnStatusUpdate.setEnabled(false);
                } else {
                    lblStatusAlert.setText("");

                    cbOrderStatus.setEnabled(true);
                    btnStatusUpdate.setEnabled(true);
                }

                btnBackToHomePage.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(this, "That's invalid! Try another.", "Invalid Burger", JOptionPane.ERROR_MESSAGE);
                txtSearchedID.requestFocus();
                txtSearchedID.setText("B");

                txtCustomerID.setText("");
                txtCustomerName.setText("");

                txtBurgerQty.setText("");

                lblTotalValue.setText("");
                cbOrderStatus.setSelectedItem("DELIVERED");
            }
        } catch (IOException ex) {
            Logger.getLogger(UpdateBurgerStatusPanel.class.getName()).log(Level.SEVERE, null, ex);
        } finally {

        }
    }//GEN-LAST:event_txtSearchedIDActionPerformed

    private void btnQTYUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQTYUpdateActionPerformed
        mainFrame.showPanel("updateQTY");
    }//GEN-LAST:event_btnQTYUpdateActionPerformed

    private void btnStatusUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatusUpdateActionPerformed
        String searchedID = txtSearchedID.getText();
        String updatedStatus = (String) cbOrderStatus.getSelectedItem();

        boolean haveAlreadyTaken;
        try {
            haveAlreadyTaken = haveAlreadyTaken = burgerController.haveAlreadyTaken(searchedID);
            if(haveAlreadyTaken) {
                Burger burger = burgerController.retrieveBurger(searchedID);
                int confirmUpdate = JOptionPane.showConfirmDialog(this, "You're about update the place?", "Confirm Update", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if(confirmUpdate==JOptionPane.YES_OPTION) {
                    burgerController.updateStatusOfRelevantBurger(searchedID, updatedStatus);
                    JOptionPane.showMessageDialog(this, "Your burger has been updated successfully!", "Burger Update", JOptionPane.INFORMATION_MESSAGE);

                    btnQTYUpdate.setEnabled(true);
                    cbOrderStatus.setEnabled(false);

                    txtSearchedID.setText("B");

                    txtCustomerID.setText("");
                    txtCustomerID.setEnabled(false);

                    txtCustomerName.setText("");
                    txtCustomerName.setEnabled(false);

                    txtBurgerQty.setText("");
                    txtBurgerQty.setEnabled(false);

                    lblTotalValue.setText("");
                    lblTotalValue.setEnabled(false);
                } else {
                    JOptionPane.showMessageDialog(this, "Your burger update has been canceled successfully!", "Burger Update Canceled", JOptionPane.INFORMATION_MESSAGE);
                    mainFrame.showPanel("dashboard");
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(UpdateBurgerStatusPanel.class.getName()).log(Level.SEVERE, null, ex);
        } finally {

        }
    }//GEN-LAST:event_btnStatusUpdateActionPerformed

    private void btnBackToHomePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToHomePageActionPerformed
        mainFrame.showPanel("dashboard");
    }//GEN-LAST:event_btnBackToHomePageActionPerformed

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        mainFrame.dispose();
        System.exit(0);
    }//GEN-LAST:event_btnCloseMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToHomePage;
    private javax.swing.JLabel btnClose;
    private javax.swing.JButton btnQTYUpdate;
    private javax.swing.JButton btnStatusUpdate;
    private javax.swing.JLabel burgerIcon;
    private javax.swing.JComboBox<String> cbOrderStatus;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JLabel lblBurgerQTY;
    private javax.swing.JLabel lblCustomerID;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblOrderID;
    private javax.swing.JLabel lblOrderStatus;
    private javax.swing.JLabel lblStatusAlert;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalValue;
    private javax.swing.JLabel lblWelcomeMessage;
    private javax.swing.JTextField txtBurgerQty;
    private javax.swing.JTextField txtCustomerID;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtSearchedID;
    // End of variables declaration//GEN-END:variables
}
