/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ihungryburger.ui.panels.search;

import ihungryburger.ui.MainFrame;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Dell
 */
public class SearchPanel extends javax.swing.JPanel {
    private MainFrame mainFrame;
    /**
     * Creates new form SearchPanel
     * @param mainFrame
     */
    public SearchPanel(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        
        Image img = new ImageIcon(getClass().getResource("/ihungryburger/resources/iHungryBurger without contiaining Texts.jpg")).getImage();
        g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcomeMessage = new javax.swing.JLabel();
        btnSearchBurger = new javax.swing.JButton();
        btnSearchCustomer = new javax.swing.JButton();
        btnSearchBestCustomer = new javax.swing.JButton();
        lblWelcomeMessage1 = new javax.swing.JLabel();
        btnBackToHomePage = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        burgerIcon = new javax.swing.JLabel();
        btnClose = new javax.swing.JLabel();

        lblWelcomeMessage.setFont(new java.awt.Font("Haettenschweiler", 0, 48)); // NOI18N
        lblWelcomeMessage.setForeground(new java.awt.Color(102, 102, 255));
        lblWelcomeMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcomeMessage.setText("iHungryBurger - Search Portal");

        btnSearchBurger.setBackground(new java.awt.Color(255, 255, 0));
        btnSearchBurger.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnSearchBurger.setText("SEARCH BURGER");
        btnSearchBurger.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnSearchBurger.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchBurgerActionPerformed(evt);
            }
        });

        btnSearchCustomer.setBackground(new java.awt.Color(0, 255, 0));
        btnSearchCustomer.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnSearchCustomer.setText("SEARCH CUSTOMER");
        btnSearchCustomer.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnSearchCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCustomerActionPerformed(evt);
            }
        });

        btnSearchBestCustomer.setBackground(new java.awt.Color(0, 255, 204));
        btnSearchBestCustomer.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnSearchBestCustomer.setText("SEARCH BEST CUSTOMER");
        btnSearchBestCustomer.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnSearchBestCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchBestCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchBestCustomerActionPerformed(evt);
            }
        });

        lblWelcomeMessage1.setFont(new java.awt.Font("Haettenschweiler", 0, 24)); // NOI18N
        lblWelcomeMessage1.setForeground(new java.awt.Color(0, 0, 204));
        lblWelcomeMessage1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcomeMessage1.setText("Search Menu Area");

        btnBackToHomePage.setBackground(new java.awt.Color(0, 51, 255));
        btnBackToHomePage.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnBackToHomePage.setForeground(new java.awt.Color(255, 255, 255));
        btnBackToHomePage.setText("Back To Home Page");
        btnBackToHomePage.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnBackToHomePage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackToHomePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToHomePageActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 0, 0));
        btnExit.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.setLabel("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        burgerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ihungryburger/resources/burger.png"))); // NOI18N

        btnClose.setBackground(new java.awt.Color(255, 0, 0));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ihungryburger/resources/close-btn.png"))); // NOI18N
        btnClose.setToolTipText("");
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWelcomeMessage1)
                    .addComponent(btnSearchBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchBestCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(511, Short.MAX_VALUE)
                        .addComponent(btnBackToHomePage, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(burgerIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblWelcomeMessage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(burgerIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWelcomeMessage)
                    .addComponent(btnClose, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(35, 35, 35)
                .addComponent(lblWelcomeMessage1)
                .addGap(18, 18, 18)
                .addComponent(btnSearchBurger)
                .addGap(18, 18, 18)
                .addComponent(btnSearchCustomer)
                .addGap(18, 18, 18)
                .addComponent(btnSearchBestCustomer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBackToHomePage)
                    .addComponent(btnExit))
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchBurgerActionPerformed
        mainFrame.showPanel("searchBurger");
    }//GEN-LAST:event_btnSearchBurgerActionPerformed

    private void btnSearchCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCustomerActionPerformed
        mainFrame.showPanel("searchCustomer");
    }//GEN-LAST:event_btnSearchCustomerActionPerformed

    private void btnSearchBestCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchBestCustomerActionPerformed
        mainFrame.showPanel("searchBestCustomer");
    }//GEN-LAST:event_btnSearchBestCustomerActionPerformed

    private void btnBackToHomePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToHomePageActionPerformed
        mainFrame.showPanel("dashboard");
    }//GEN-LAST:event_btnBackToHomePageActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        mainFrame.dispose();
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        mainFrame.dispose();
        System.exit(0);
    }//GEN-LAST:event_btnCloseMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToHomePage;
    private javax.swing.JLabel btnClose;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSearchBestCustomer;
    private javax.swing.JButton btnSearchBurger;
    private javax.swing.JButton btnSearchCustomer;
    private javax.swing.JLabel burgerIcon;
    private javax.swing.JLabel lblWelcomeMessage;
    private javax.swing.JLabel lblWelcomeMessage1;
    // End of variables declaration//GEN-END:variables
}
