/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ihungryburger.ui.panels.search;

import ihungryburger.controller.BurgerController;
import ihungryburger.ui.MainFrame;
import ihungryburger.model.Burger;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class SearchBurgerPanel extends javax.swing.JPanel {
    private MainFrame mainFrame;
    public BurgerController burgerController;
    /**
     * Creates new form SearchBurgerPanel
     * @param mainFrame
     */
    public SearchBurgerPanel(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
        burgerController = new BurgerController();
        
        txtSearchedID.setText("B");
        txtSearchedID.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblOrderID = new javax.swing.JLabel();
        txtSearchedID = new javax.swing.JTextField();
        lblWelcomeMessage = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        lblCustomerID = new javax.swing.JLabel();
        lblCustomerIDValue = new javax.swing.JLabel();
        lblCustomerName = new javax.swing.JLabel();
        lblCustomerNameValue = new javax.swing.JLabel();
        lblQTY = new javax.swing.JLabel();
        lblQTYValue = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblTotalValue = new javax.swing.JLabel();
        lblOrderStatus = new javax.swing.JLabel();
        lblOrderStatusValue = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnBackToHomePage = new javax.swing.JButton();
        burgerIcon = new javax.swing.JLabel();
        btnClose = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 102, 255));

        lblOrderID.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        lblOrderID.setText("Enter Order ID:");

        txtSearchedID.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        txtSearchedID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchedIDActionPerformed(evt);
            }
        });

        lblWelcomeMessage.setFont(new java.awt.Font("Haettenschweiler", 0, 48)); // NOI18N
        lblWelcomeMessage.setForeground(new java.awt.Color(204, 204, 255));
        lblWelcomeMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcomeMessage.setText("iBurgerHungry - Search Burger Details");

        btnSearch.setBackground(new java.awt.Color(51, 204, 0));
        btnSearch.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("SEARCH");
        btnSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        lblCustomerID.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        lblCustomerID.setText("Customer ID:");

        lblCustomerIDValue.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N

        lblCustomerName.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        lblCustomerName.setText("Name:");

        lblCustomerNameValue.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N

        lblQTY.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        lblQTY.setText("QTY:");

        lblQTYValue.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N

        lblTotal.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        lblTotal.setText("Total:");

        lblTotalValue.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N

        lblOrderStatus.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        lblOrderStatus.setText("Order Status:");

        lblOrderStatusValue.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N

        btnBackToHomePage.setBackground(new java.awt.Color(0, 51, 255));
        btnBackToHomePage.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnBackToHomePage.setForeground(new java.awt.Color(255, 255, 255));
        btnBackToHomePage.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnBackToHomePage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackToHomePage.setLabel("BACK TO HOME PAGE");
        btnBackToHomePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToHomePageActionPerformed(evt);
            }
        });

        burgerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ihungryburger/resources/burger.png"))); // NOI18N

        btnClose.setBackground(new java.awt.Color(255, 0, 0));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ihungryburger/resources/close-btn.png"))); // NOI18N
        btnClose.setToolTipText("");
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 51, 255));
        btnBack.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblOrderID)
                                    .addComponent(burgerIcon))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtSearchedID, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblWelcomeMessage)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblOrderStatus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblOrderStatusValue, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCustomerID)
                                    .addComponent(lblCustomerName)
                                    .addComponent(lblQTY)
                                    .addComponent(lblTotal))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblTotalValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCustomerIDValue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                                    .addComponent(lblCustomerNameValue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblQTYValue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBackToHomePage, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnClose)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblWelcomeMessage)
                            .addComponent(burgerIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrderID)
                    .addComponent(txtSearchedID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomerIDValue)
                    .addComponent(lblCustomerID))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomerName)
                    .addComponent(lblCustomerNameValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQTYValue)
                    .addComponent(lblQTY))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(lblTotalValue))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrderStatus)
                    .addComponent(lblOrderStatusValue)
                    .addComponent(btnBackToHomePage)
                    .addComponent(btnBack))
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchedIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchedIDActionPerformed
        btnSearch.requestFocus();
        btnSearch.doClick();
    }//GEN-LAST:event_txtSearchedIDActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String searchedID = txtSearchedID.getText();

        boolean haveAlreadyTaken;
        try {
            haveAlreadyTaken = burgerController.haveAlreadyTaken(searchedID);
            if(haveAlreadyTaken) {
                Burger burger = burgerController.retrieveBurger(searchedID);
                lblCustomerIDValue.setText(burger.getCustomerID());
                lblCustomerNameValue.setText(burger.getCustomerName());

                lblQTYValue.setText(String.valueOf(burger.getBurgerQty()));

                double total = burger.getBurgerQty()*Burger.BURGERPRICE;
                lblTotalValue.setText(String.valueOf(total));

                lblOrderStatusValue.setText(burgerController.getStatusInTextMode(burger.getStatus()));
            } else {
                JOptionPane.showMessageDialog(this, "That's invalid! Try another.", "Invalid Burger", JOptionPane.ERROR_MESSAGE);
                txtSearchedID.requestFocus();
                txtSearchedID.setText("B");

                lblCustomerIDValue.setText("");
                lblCustomerNameValue.setText("");

                lblQTYValue.setText("");

                lblTotalValue.setText("");
                lblOrderStatusValue.setText("");
            }
        } catch (IOException ex) {
            Logger.getLogger(SearchBurgerPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnBackToHomePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToHomePageActionPerformed
        mainFrame.showPanel("dashboard");
    }//GEN-LAST:event_btnBackToHomePageActionPerformed

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        mainFrame.dispose();
        System.exit(0);
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        mainFrame.showPanel("viewBurgers");
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBackToHomePage;
    private javax.swing.JLabel btnClose;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel burgerIcon;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCustomerID;
    private javax.swing.JLabel lblCustomerIDValue;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblCustomerNameValue;
    private javax.swing.JLabel lblOrderID;
    private javax.swing.JLabel lblOrderStatus;
    private javax.swing.JLabel lblOrderStatusValue;
    private javax.swing.JLabel lblQTY;
    private javax.swing.JLabel lblQTYValue;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalValue;
    private javax.swing.JLabel lblWelcomeMessage;
    private javax.swing.JTextField txtSearchedID;
    // End of variables declaration//GEN-END:variables
}
